---
- name: Metrics | Make sure Helm is installed
  command: "{{ bin_dir }}/helm version"
  register: helm_ready_result
  until: helm_ready_result|succeeded
  retries: 4
  delay: 5
  when:
    - prometheus_operator_enabled
    - inventory_hostname == groups['kube-master'][0]

- name: Metrics | Add coreos repo
  command: "{{ bin_dir }}/helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/"
  when:
    - prometheus_operator_enabled
    - inventory_hostname == groups['kube-master'][0]
  run_once: true

- name: Metrics | Install Prometheus Operator
  command: "{{ bin_dir }}/helm upgrade --install prometheus-operator coreos/prometheus-operator --namespace {{ monitoring_namespace }}"
  when:
    - prometheus_operator_enabled
    - inventory_hostname == groups['kube-master'][0]
  run_once: true

- name: Metrics | Install K8s cluster metrics
  command: "{{ bin_dir }}/helm upgrade --install kube-prometheus     coreos/kube-prometheus     --namespace {{ monitoring_namespace }}"
  when:
    - prometheus_operator_enabled
    - k8s_metrics_enabled
    - inventory_hostname == groups['kube-master'][0]
  run_once: true
